In [12]:
import needle as ndl
import numpy as np
from needle import backend_ndarray as nd

Import Error!!


metal()

In [6]:
data = np.arange(0, 216).reshape((9, 8, 3))
weight = np.arange(0, 36).reshape(3, 12)

In [11]:
tensor = ndl.Tensor(data, device=ndl.metal())
weight_tensor = ndl.Tensor(weight, device=ndl.metal())

Import Error!!


AttributeError: 'NoneType' object has no attribute 'Array'

In [4]:
splitted_tuple = ndl.ops.split(tensor, axis=0)

In [7]:
(splitted_tuple[0]@weight_tensor)

needle.Tensor([[  60.   63.   66.   69.   72.   75.   78.   81.   84.   87.   90.   93.]
 [ 168.  180.  192.  204.  216.  228.  240.  252.  264.  276.  288.  300.]
 [ 276.  297.  318.  339.  360.  381.  402.  423.  444.  465.  486.  507.]
 [ 384.  414.  444.  474.  504.  534.  564.  594.  624.  654.  684.  714.]
 [ 492.  531.  570.  609.  648.  687.  726.  765.  804.  843.  882.  921.]
 [ 600.  648.  696.  744.  792.  840.  888.  936.  984. 1032. 1080. 1128.]
 [ 708.  765.  822.  879.  936.  993. 1050. 1107. 1164. 1221. 1278. 1335.]
 [ 816.  882.  948. 1014. 1080. 1146. 1212. 1278. 1344. 1410. 1476. 1542.]])

In [7]:
weight_tensor.grad

needle.Tensor([[ 84.  84.  84.  84.  84.  84.  84.  84.  84.  84.  84.  84.]
 [ 92.  92.  92.  92.  92.  92.  92.  92.  92.  92.  92.  92.]
 [100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.]])

In [8]:
weight_tensor.requires_grad

True

In [9]:
import torch
import needle.nn as nn
seq_length = 7
num_layers = 3
batch_size = 6
input_size = 3
hidden_size = 5
bias = False
init_hidden = True
nonlinearity = 'relu'
device = ndl.cpu()

In [10]:
# x = np.random.randn(batch_size, input_size).astype(np.float32)
# h0 = np.random.randn(batch_size, hidden_size).astype(np.float32)
# c0 = np.random.randn(batch_size, hidden_size).astype(np.float32)
# model = nn.LSTMCell(input_size, hidden_size, device=device)
# # model_tch = torch.lstm_cell(x, (h0, c0), )
# mugrade_submit(model.W_hh.numpy())
# (h, c) = model(ndl.Tensor(x, device=device), (ndl.Tensor(h0, device=device), ndl.Tensor(c0, device=device)))
# # mugrade_submit(h.numpy())
# # mugrade_submit(c.numpy())
# h.sum().backward()
# # mugrade_submit(model.W_hh.grad.numpy())

In [13]:
np.random.seed(3)
model = nn.LSTMCell(input_size, hidden_size, device=device)
model.W_hh.numpy().shape

(3, 5)

In [14]:
model = nn.RNNCell(input_size, hidden_size, device=device)
model.W_hh.numpy().shape

(5, 5)